### ISSUE TITLE
apecs-stm-0.1.4 fails to build with apecs-0.9.2

### ISSUE THREAD

**Issue by dpwiz** [jonascarpay/apecs#81]
```
Building library for apecs-stm-0.1.4..   
[1 of 2] Compiling Apecs.STM             
                      
/tmp/stack-c53d58dfa7c9502e/apecs-stm-0.1.4/src/Apecs/STM.hs:43:62: error:
    Module ‘Apecs.TH’ does not export ‘makeMapComponentsFor’
   |                  
43 | import           Apecs.TH                    (makeWorldNoEC, makeMapComponentsFor)
   |                                                              ^^^^^^^^^^^^^^^^^^^^
```

And apecs-0.9.3 is not on Hackage.

**Comment by jonascarpay** [comment]
Oops, thanks for letting me know.

I've pushed 0.9.3 to hackage, and bumped the minimum requirement in apecs-stm in 07227c04847a12af78fce866116b444a2e09f819. As soon as 0.9.3 is green on hackage I will upload the new apecs-stm and then we should be good.

**Comment by jonascarpay** [comment]
Alright, I've pushed apecs-stm-0.1.5. When you get a chance, please check if that solved the issue.

**Comment by dpwiz** [comment]
It works :ok_hand:
